development:
  adapter: sqlite3
  encoding: unicode
  database: db/trmnl_byos_sinatra.sqlite3

production:
  adapter: sqlite3
  encoding: unicode
  database: db/trmnl_byos_sinatra.sqlite3

test:
  adapter: sqlite3
  database: ":memory:"

#if you want to use a database you already have
# install the relevant gem, and then you  
# can replace the production block above
#eg postgres
#production:
#  adapter: postgresql
#  encoding: unicode
#  database: trmnl_byos_sinatra
#  pool: 2
#  username: your_username
#  password: your_password
